repos:
  # Removes output and empty cells as well as metadata
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        args: [--strip-empty-cells]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      # Upgrades python style
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.31.1]
        args: [--nbqa-mutate, --py38-plus]
      # Sorts imports
      - id: nbqa-isort
        additional_dependencies: [isort==5.10.1]
        args: [--nbqa-mutate]
      # Formats code
      - id: nbqa-black
        additional_dependencies: [black==22.3.0]
        args: [--nbqa-mutate]
      # Detects code smells
      - id: nbqa-flake8
      # Checks that python code is valid
      - id: nbqa-check-ast

  # Checks for common spelling errors
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        types: [file]
        types_or: [python, pyi, markdown, rst, jupyter]
        args: [-L doas]
