channels:
  - conda-forge
dependencies:
  # Jupyter
  - jupyterlab=3
  - jupyterlab-spellchecker
  - jupyterlab_code_formatter
  - jupyterlab-drawio
  - jupyterlab-autosave-on-focus-change
  - jupyterlab-system-monitor
  # Python Kernel
  - ipykernel>5.1
  - python=3.8
  # update outdated repo2docker version
  - pip
  - pip:
      - -r pyglotaran-requirements.txt
